---
- name: Hello World!
  hosts: all
  gather_facts: False
 
  tasks:

  - name: Instal Python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python2 python-simplejson)
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."